export interface IItem {
  id: string;
  name: string;
  image: string;
  totalQty: number;
  blockWidth: number;
  blockHeight: number;
  placementAmount: number;
  placementSet: "horizontal" | "vertical";
  place_main_rak: boolean;
  place_drawer_atas: boolean;
  place_door: boolean;
  place_freezer: boolean;
  view_isometric: boolean;
  view_front: boolean;
  view_front_upper: boolean;
  category: string;
  dock: "top" | "bottom";
  rack: TRack;
}

export type TRack =
  | "top-left-door"
  | "top-middle-door"
  | "top-right-door"
  | "middle-left-door"
  | "middle-right-door"
  | "bottom-left-door"
  | "bottom-right-door"
  | "freezer-left-door"
  | "freezer-right-door"
  | "freezer-sec2-left-door"
  | "freezer-sec2-right-door";

const refrigeratorItems: IItem[] = [
  {
    id: "egg",
    name: "Egg (dengan alas)",
    blockWidth: 2,
    blockHeight: 3,
    placementSet: "horizontal",
    placementAmount: 1,
    totalQty: 1,
    place_main_rak: true,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Food",
    image: "/items/egg-front-view.webp",
    dock: "top",
    rack: "top-left-door",
  },
  {
    id: "puding",
    name: "Puding",
    blockWidth: 3,
    blockHeight: 3,
    placementSet: "horizontal",
    placementAmount: 1,
    totalQty: 1,
    place_main_rak: true,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Food",
    image: "/items/pudding-front-view.webp",
    dock: "bottom",
    rack: "bottom-left-door",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 12,
    totalQty: 12,
    place_main_rak: true,
    place_drawer_atas: true,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/strawberry-front-view.webp",
    dock: "top",
    rack: "top-middle-door",
  },
  {
    id: "banana",
    name: "Banana",
    blockWidth: 1,
    blockHeight: 3,
    placementSet: "vertical",
    placementAmount: 5,
    totalQty: 5,
    place_main_rak: true,
    place_drawer_atas: true,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/banana-front-view.webp",
    dock: "bottom",
    rack: "middle-left-door",
  },
  {
    id: "brownies",
    name: "Brownies",
    blockWidth: 3,
    blockHeight: 2,
    placementSet: "horizontal",
    placementAmount: 1,
    totalQty: 1,
    place_main_rak: true,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Food",
    image: "/items/brownie-front-view.webp",
    dock: "top",
    rack: "top-right-door",
  },
  {
    id: "cheese",
    name: "Cheese",
    blockWidth: 2,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 3,
    totalQty: 3,
    place_main_rak: true,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Food",
    image: "/items/cheese-front-view.webp",
    dock: "bottom",
    rack: "bottom-right-door",
  },
  {
    id: "roti_tawar",
    name: "Roti Tawar",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 9,
    totalQty: 9,
    place_main_rak: true,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Food",
    image: "/items/bread-front-view.webp",
    dock: "top",
    rack: "top-left-door",
  },
  {
    id: "wortel",
    name: "Wortel",
    blockWidth: 1,
    blockHeight: 2,
    placementSet: "vertical",
    placementAmount: 6,
    totalQty: 6,
    place_main_rak: false,
    place_drawer_atas: true,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/carrot-front-view.webp",
    dock: "bottom",
    rack: "bottom-left-door",
  },
  {
    id: "kentang",
    name: "Kentang",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 4,
    totalQty: 4,
    place_main_rak: false,
    place_drawer_atas: true,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/potato-front-view.webp",
    dock: "top",
    rack: "top-middle-door",
  },
  {
    id: "jagung",
    name: "Jagung",
    blockWidth: 1,
    blockHeight: 2,
    placementSet: "vertical",
    placementAmount: 4,
    totalQty: 4,
    place_main_rak: true,
    place_drawer_atas: true,
    place_door: false,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "",
    dock: "bottom",
    rack: "middle-right-door",
  },
  {
    id: "botol",
    name: "Botol",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 10,
    totalQty: 10,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: true,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Drink",
    image: "/items/bottle-front-view.webp",
    dock: "top",
    rack: "top-right-door",
  },
  {
    id: "susu_karton",
    name: "Susu Karton",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 6,
    totalQty: 6,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: true,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Drink",
    image: "/items/milk-front-view.webp",
    dock: "bottom",
    rack: "bottom-right-door",
  },
  {
    id: "jar",
    name: "Jar",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 8,
    totalQty: 8,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: true,
    place_freezer: false,
    view_isometric: true,
    view_front: true,
    view_front_upper: false,
    category: "Food",
    image: "/items/jar-front-view.webp",
    dock: "top",
    rack: "top-left-door",
  },
  {
    id: "ice_cream",
    name: "Ice Cream",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 8,
    totalQty: 8,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Drink",
    image: "/items/ice-cream-front-view.webp",
    dock: "bottom",
    rack: "freezer-left-door",
  },
  {
    id: "ice_stick_kiko",
    name: "Ice Stick (Kiko)",
    blockWidth: 1,
    blockHeight: 2,
    placementSet: "vertical",
    placementAmount: 2,
    totalQty: 2,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Drink",
    image: "",
    dock: "top",
    rack: "freezer-right-door",
  },
  {
    id: "dumpling",
    name: "Dumpling",
    blockWidth: 1,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 4,
    totalQty: 4,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/dumpling-front-view.webp",
    dock: "top",
    rack: "freezer-sec2-left-door",
  },
  {
    id: "ayam",
    name: "Ayam",
    blockWidth: 2,
    blockHeight: 2,
    placementSet: "horizontal",
    placementAmount: 4,
    totalQty: 4,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/chicken-front-view.webp",
    dock: "top",
    rack: "freezer-sec2-right-door",
  },
  {
    id: "sausage",
    name: "Sausage",
    blockWidth: 1,
    blockHeight: 2,
    placementSet: "vertical",
    placementAmount: 4,
    totalQty: 4,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "",
    dock: "bottom",
    rack: "freezer-left-door",
  },
  {
    id: "ikan",
    name: "Ikan",
    blockWidth: 1,
    blockHeight: 3,
    placementSet: "vertical",
    placementAmount: 3,
    totalQty: 3,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/fish-front-view.webp",
    dock: "bottom",
    rack: "freezer-right-door",
  },
  {
    id: "daging",
    name: "Daging",
    blockWidth: 3,
    blockHeight: 1,
    placementSet: "horizontal",
    placementAmount: 3,
    totalQty: 3,
    place_main_rak: false,
    place_drawer_atas: false,
    place_door: false,
    place_freezer: true,
    view_isometric: true,
    view_front: true,
    view_front_upper: true,
    category: "Food",
    image: "/items/meat-front-view.webp",
    dock: "top",
    rack: "freezer-sec2-left-door",
  },
];

export default refrigeratorItems;
